### ISSUE TITLE
Scheduled task runs twice sometimes.

### ISSUE THREAD

**Issue by konuch** [slolam/XecMe#5]
My application is hosted on azure as a web app. During start up it initializes scheduled tasks using XecMe which is located in another assembly. My scheduled task is configured to send me an email every day at 00:00. Once in a while I happen to receive two emails per given day.
Here's my config class:

```
namespace XecMeTest
{
    public static class XecMeTest
    {
        private static bool _initialized;

        // Initialize scheduled task manager
        public static void Init()
        {
            if (!_initialized)
            {
                var config = new FlowConfiguration();

                //task to run every day starting from today
                config.ScheduledTask<DailyTasks>("DailyTasks", LogType.Information)
                    .RunDaily()
                    .RepeatEvery(1) // every day
                    .StartsFrom(DateTime.Today)
                    .RunsAt(TimeSpan.Parse("00:00"))
                    .OfTimeZone("Central Europe Standard Time")  //use Central Europe Standard Time or Pacific Standard Time 
                    .Add();

                TaskManager.Start(config);

                _initialized = true;
            }
        }
    }
}
```

And here's my daily tasks class:

```
namespace Tasks
{
    public class DailyTasks : Task
    {
        public override ExecutionState OnExecute(ExecutionContext context)
        {
            //Here I'm sending the email.
            sendMeAnEmail();

            return base.OnExecute(context);
        }
    }

    public class Task : ITask
    {
        public virtual void OnStart(ExecutionContext context){ }
        public virtual void OnStop(ExecutionContext context) { }
        public virtual void OnUnhandledException(Exception e){ }
        public virtual ExecutionState OnExecute(ExecutionContext context)
        {
            return ExecutionState.Executed;
        }
    }
}
```

Do you have an idea why this keeps happening?

**Comment by slolam** [comment]
Let me take a look at it. Will get back to you.

**Comment by slolam** [comment]
I took a peek at code, Scheduled job would not run twice for a same instance. If you have 2 instances Web app running which could be the case when scaled out to more than 1 instance during peak load. It would likely trigger the Send email task twice once on each instance. If you check your Azure subscription whether there were 2 instances of the app running during your peak load.

Also, if you can share the logs for the XecMe, I would be able to troubleshoot it better. Please let me know if you can share logs.

Thanks

**Comment by konuch** [comment]
Hey, I will take a look at the instance count, but I'm affraid it won't be the case, because I am running it on dev instance, which is not under load at all, so it shouldn't scale. Is it possible to configure logging to a file using the flow configuration?

**Comment by slolam** [comment]
Yes, you can configure the log by using before you call the `TaskManager.Start()`

`XecMe.Common.Diagnostics.Log.ErrorSink = new XecMe.Common.Diagnostics.Write(your error log delegate);`

`XecMe.Common.Diagnostics.Log.InformationSink = new XecMe.Common.Diagnostics.Write(your information log delegate);`

`XecMe.Common.Diagnostics.Log.WarningSink = new XecMe.Common.Diagnostics.Write(your information log delegate);`

**Comment by slolam** [comment]
If you are running off of dev environment, then can you capture the host (Azure VM running web app) details as part of the email? That way we can zero on whether both emails are generated from single instance or 2 different instances

**Comment by konuch** [comment]
Hey, thanks for the ideas. I've included the instance ID into the email message and also enabled logging based on your example. Will post the log data as soon as it happens again.
Tip: Maybe it would be worth including the logging example into readme, just my 2 cents :)

Thanks.

**Comment by slolam** [comment]
@konuch, updated the ReadMe with Logging section, thanks for the tip :-) Didn't get a chance to work on this. 
Did you get any success in identifying the issue of generating 2 emails? Can I help you with identifying the issue if it's critical?

**Comment by konuch** [comment]
Hey, good job updating the readme. 
The issue with 2 emails haven't occured since we discussed it last time. It keeps sending me 1 email per day containing an azure instance ID, altough the ID changes after a few days, but as I said it's just one mail per day so far.

**Comment by slolam** [comment]
@konuch, you are right the instance changes every few days and if your task runs when an old instance is being recycled with new one, there is a chance that task runs on both instances. However it is rare but we see similar pattern. Unless we see at least one occurrence of 2 emails with the instance ID on it we can't say it for sure.

**Comment by konuch** [comment]
@slolam, so it just occured. I've received two emails. 
The azure webapp instance ID was same in both e-mails.
I've got the logs as a CSV file, where could I upload them so you could take a look?

**Comment by slolam** [comment]
@konuch, if log does not contain any sensitive information, could you please upload it here? Just drag and drop where you are typing the comments

**Comment by konuch** [comment]
Hey, here's a zip with the log export. You might see some exceptions there, but those are caused by a fall back check I've implemented. So dont get confused by those.
[applogtable.zip](https://github.com/slolam/XecMe/files/586746/applogtable.zip)

**Comment by slolam** [comment]
@konuch: Here is the reason why it's firing twice and triggering email. If the task triggers a second before and due to the exception it completes in sub second gets rescheduled for the same time for daily schedule. I'll work on it.

**Comment by slolam** [comment]
@konuch, pushed the fix to [issues/5](https://github.com/slolam/XecMe/tree/issues/5). I would appreciate if you could please pull the code from this branch and test it. I would need logs for couple of days. Your case is edge case and seem very interesting issue to fix :-) 

Thanks in anticipation.

**Comment by konuch** [comment]
Ok, I'll try your fix and keep you updated.

**Comment by slolam** [comment]
@konuch thanks 👍

**Comment by konuch** [comment]
Hey, I'm uploading a new set of logs. It hasnt occured yet, so it's looking good so far.

[applogtable_29-11-2016.zip](https://github.com/slolam/XecMe/files/619756/applogtable_29-11-2016.zip)

**Comment by konuch** [comment]
If you find it possible, could you release this fix in a new release, so I can reference this in my package config. We're having a version release tommorow and I'd like to include this fix in it, if possible.

**Comment by slolam** [comment]
I looked at the logs and it didn't seem to me that the condition occurred that caused multiple runs.

I'll build new version and publish it today. Thanks for helping me out to find the issue.

**Comment by slolam** [comment]
@konuch, pushed new package. If everything is works, please close this issue.

Thanks.

**Comment by konuch** [comment]
Thanks.
