### ISSUE TITLE
Flow config fails when task is scheduled to run on day 1.

### ISSUE THREAD

**Issue by konuch** [slolam/XecMe#6]
Hey it's me again.
I'm attempting to build a scheduled task which runs on first day every month of the year. 
Here's my config:

```
config.ScheduledTask<MonthlyTasks>("MonthlyTasks", LogType.All)
 .RunByDaysOfTheMonths(Months.All)
 .OnDays(1)
 .RunsAt(TimeSpan.Parse("10:30"))
 .OfLocalTimeZone()
 .Add();                
```

This fails with:

```
An exception of type 'System.InvalidOperationException' occurred in XecMe.Core.dll but was not handled in user code

Additional information: Missing the attributes for the Monthly task
```

However when I change the " .OnDays(1)" to  ".OnDays(2)" or any other valid day number except 1, it runs Ok.

**Comment by slolam** [comment]
Let me take a look. I will get back to you

**Comment by slolam** [comment]
@konuch, just fixed and pushed the code as well as NuGet package version v2.1.3

**Comment by slolam** [comment]
@konuch, please close the issue if it works for you.

**Comment by konuch** [comment]
Hey, thanks it's working.

**Comment by slolam** [comment]
@konuch, thanks for identifying the issue.
